"""empty message

Revision ID: 041781ab1e4b
Revises: ff04682e9932
Create Date: 2018-02-03 14:45:27.954102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041781ab1e4b'
down_revision = 'ff04682e9932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('allowance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'allowance')
    # ### end Alembic commands ###
