"""empty message

Revision ID: 6dbe242c2728
Revises: 80ba315a6e0c
Create Date: 2018-01-28 22:58:56.455119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbe242c2728'
down_revision = '80ba315a6e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserCache', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserCache', 'active')
    # ### end Alembic commands ###
