"""empty message

Revision ID: 80ba315a6e0c
Revises: 
Create Date: 2018-01-28 14:12:10.707042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ba315a6e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profiles',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metro', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('companyName_0', sa.Text(), nullable=True),
    sa.Column('companyUrl_0', sa.Text(), nullable=True),
    sa.Column('title_0', sa.Text(), nullable=True),
    sa.Column('start_date_0', sa.Date(), nullable=True),
    sa.Column('end_date_0', sa.Date(), nullable=True),
    sa.Column('summary_0', sa.Text(), nullable=True),
    sa.Column('companyName_1', sa.Text(), nullable=True),
    sa.Column('companyUrl_1', sa.Text(), nullable=True),
    sa.Column('title_1', sa.Text(), nullable=True),
    sa.Column('start_date_1', sa.Date(), nullable=True),
    sa.Column('end_date_1', sa.Date(), nullable=True),
    sa.Column('summary_1', sa.Text(), nullable=True),
    sa.Column('companyName_2', sa.Text(), nullable=True),
    sa.Column('companyUrl_2', sa.Text(), nullable=True),
    sa.Column('title_2', sa.Text(), nullable=True),
    sa.Column('start_date_2', sa.Date(), nullable=True),
    sa.Column('end_date_2', sa.Date(), nullable=True),
    sa.Column('summary_2', sa.Text(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.Column('education_school', sa.Text(), nullable=True),
    sa.Column('education_start', sa.Date(), nullable=True),
    sa.Column('education_end', sa.Date(), nullable=True),
    sa.Column('education_degree', sa.Text(), nullable=True),
    sa.Column('education_study_field', sa.Text(), nullable=True),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('recruiter_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('current_session_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserCache',
    sa.Column('cache_id', sa.String(length=16), nullable=False),
    sa.Column('friendly_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('User_Records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['Profiles.member_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'member_id')
    )
    op.create_table('Cache_Records',
    sa.Column('cache_id', sa.String(length=16), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cache_id'], ['UserCache.cache_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['Profiles.member_id'], ),
    sa.PrimaryKeyConstraint('cache_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cache_Records')
    op.drop_table('User_Records')
    op.drop_table('UserCache')
    op.drop_table('Users')
    op.drop_table('Profiles')
    # ### end Alembic commands ###
