"""empty message

Revision ID: 0faa41db8aef
Revises: bb74dc14138c
Create Date: 2018-02-03 05:40:25.576042

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0faa41db8aef'
down_revision = 'bb74dc14138c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserActivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('new_records', sa.Integer(), nullable=True),
    sa.Column('borrowed_records', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserActivity')
    # ### end Alembic commands ###
