"""empty message

Revision ID: 399897c8f915
Revises: e68c396ecded
Create Date: 2018-02-13 00:05:27.375464

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '399897c8f915'
down_revision = 'e68c396ecded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profiles', sa.Column('first_graduation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Profiles', 'first_graduation_date')
    # ### end Alembic commands ###
