"""empty message

Revision ID: 7234551b3b95
Revises: 02b6bec59f0f
Create Date: 2018-03-18 01:21:00.540017

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7234551b3b95'
down_revision = '02b6bec59f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_email', sa.Boolean(), nullable=True),
    sa.Column('is_website', sa.Boolean(), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
