"""empty message

Revision ID: a2bc5893a412
Revises: 0faa41db8aef
Create Date: 2018-02-04 06:00:12.478956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a2bc5893a412'
down_revision = '0faa41db8aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('allowance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'allowance')
    # ### end Alembic commands ###
