"""empty message

Revision ID: e68c396ecded
Revises: a2bc5893a412
Create Date: 2018-02-10 04:45:45.583633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e68c396ecded'
down_revision = 'a2bc5893a412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profiles', sa.Column('careerInterests', sa.Boolean(), nullable=True))
    op.add_column('Profiles', sa.Column('isCompanyFollower', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Profiles', 'isCompanyFollower')
    op.drop_column('Profiles', 'careerInterests')
    # ### end Alembic commands ###
